branches:
  only:
  - master

addons:
  apt:
    packages:
      - aspell
      - aspell-en

script:
  scripts/checkSpelling.sh

notifications:
  email:
    recipients:
      - $EMAIL1
    on_success: always
    on_failure: always
